using MediatR;

namespace ScientificWork.UseCases.Professors.GetProfessorScientificPortfolio;

public class GetProfessorScientificPortfolioCommand : IRequest<GetProfessorScientificPortfolioCommandResult>;