using MediatR;

namespace ScientificWork.UseCases.Professors.GetProfessorScientificPortfolio;

public record GetProfessorScientificPortfolioQuery : IRequest<GetProfessorScientificPortfolioQueryResult>;